### ISSUE TITLE
Set connection on-the-fly

### ISSUE THREAD

**Issue by DraperStudio** [vinkla/facebook#5]
Is there any way to a set connection on-the-fly through an array without having them defined in the configuration file?

```php
Facebook::connection([
    'app_id' => 'your-app-id',
    'app_secret' => 'your-app-scret',
    'default_graph_version' => 'v2.4',
])->get('/me');
```

**Comment by vinkla** [comment]
No, I don't think so. Sorry.

**Comment by vinkla** [comment]
Out of curiosity; why would you want that though?

**Comment by DraperStudio** [comment]
I am developing an application where users have to add their own Facebook applications so that these can be used for things like subscribing, newsletters and such things.

That means these applications would never be in the configuration file of my application but retrieved from the database.

**Comment by DraperStudio** [comment]
Solved it like that for now.

```php
Config::set('facebook.connections.'.$tempConnectionKey, [
    'app_id' => 'your-app-id',
    'app_secret' => 'your-app-scret',
    'default_graph_version' => 'v2.4',
]);
```

**Comment by vinkla** [comment]
Okay, good.

**Comment by GrahamCampbell** [comment]
I wouldn't recommend doing that.

**Comment by GrahamCampbell** [comment]
I'd recommend using the `FacebookFactory` and calling it's make method.

**Comment by GrahamCampbell** [comment]
@DraperStudio That should be the same deal as setting the connection on the fly, right?

**Comment by DraperStudio** [comment]
@GrahamCampbell Do you mean like this?

```php
$response = app('facebook.factory')->make([
    'app_id' => 'your-app-id',
    'app_secret' => 'your-app-scret',
    'default_graph_version' => 'v2.4',
])->get('/me');
```

**Comment by GrahamCampbell** [comment]
Yes, or, you can have `app(FacebookFactory::class)->...`, or, inject a `FacebookFactory` instance if you want.

**Comment by DraperStudio** [comment]
Thanks for the tip, will use this method instead now.
